In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import platform
from matplotlib import font_manager, rc 
import matplotlib
# '-' 부호가 제대로 표시되게 하는 설정 
matplotlib.rcParams['axes.unicode_minus'] = False
# 운영 체제마다 한글이 보이게 하는 설정 # 윈도우
if platform.system() == 'Windows':
    path = "c:\Windows\Fonts\malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name() 
    rc('font', family=font_name)
#맥
elif platform.system() == 'Darwin': 
    rc('font', family='AppleGothic')
# 리눅스
elif platform.system() == 'Linux':
    rc('font', family='NanumBarunGothic')


In [4]:
!pip install xlrd xlwt
!pip install openpyxl

In [6]:
data_series = pd.Series([1, 2, 3, 4, 5, 'A', 'B', 'C', '가', '나', '다'])
print(data_series)
print(type(data_series))

0     1
1     2
2     3
3     4
4     5
5     A
6     B
7     C
8     가
9     나
10    다
dtype: object
<class 'pandas.core.series.Series'>


In [9]:
# 두개의 리스트로 인덱스 설정
data_series1 = pd.Series([1, 2, 3, 4, 5, 'A', 'B', 'C', '가', '나', '다'], ['a','b','c','d','e','f','g','h','i','k','k'])
print(data_series1)

# index의 인수로 인덱스 설정
data_series2 = pd.Series([1, 2, 3, 4, 5, 'A', 'B', 'C', '가', '나', '다'], index = ['a','b','c','d','e','f','g','h','i','k','k']
)
print(data_series2)

a    1
b    2
c    3
d    4
e    5
f    A
g    B
h    C
i    가
k    나
k    다
dtype: object
a    1
b    2
c    3
d    4
e    5
f    A
g    B
h    C
i    가
k    나
k    다
dtype: object


In [12]:
data_series3 = pd.Series(({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}))
print(data_series3)

data_series4 = pd.Series(({'a': 1, 'b': 2, 'c': 3, 'c': 4, 'e': 5}))
# 딕셔너리의 중복된 키(key)에 해당하는 값(value)은 마지막 값으로 덮어씀
print(data_series4)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    4
e    5
dtype: int64


In [14]:
data_frame = pd.DataFrame({"A": [1,2,3,4], "B": [5,6,7,8]})
print(data_frame)
print(type(data_frame))

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
<class 'pandas.core.frame.DataFrame'>


In [15]:
data_frame2 = pd.DataFrame([[1,5], [2,6], [3,7], [4,8]], columns=['A', 'B'])
print(data_frame2)
print(type(data_frame2))

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
<class 'pandas.core.frame.DataFrame'>


### 람다 함수

-람다함수를 통해 이름이 없는 함수를 만들 수 있습니다.

-람다함수의 장점은 코드의 간결함 메모리의 절약이라고 생각할 수 있습니다.

      lambda x : x + 1


In [16]:
fc = lambda x : x + 1
fc(10)

11

In [24]:
f = lambda x : x.max() - x.min()

df = pd.DataFrame(np.arange(0, 12, 1).reshape(4,3), columns = ['A', 'B', 'C'], index = ['a', 'b', 'c', 'd'])
# np.arange(0, 12, 1).reshape(4,3)
print(df)

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11


In [25]:
df.apply(f, 0) # 0은 열기준

A    9
B    9
C    9
dtype: int64

In [26]:
df.apply(f, 1) # 1은 행기준

a    2
b    2
c    2
d    2
dtype: int64

In [27]:
df.apply(fc)

A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

# CSV 파일 읽어오기, EXCEL 파일 읽어오기

In [32]:
import numpy as np
import pandas as pd
data = pd.read_excel("sample.xlsx")
print(data)

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0          NaN         학번    프로그래밍기초     빅데이터분석       AI활용
1          NaN     201001         64         60         84
2          NaN     201002         98         55         79
3          NaN     201003         82         94        100
4          NaN     201004         69         93         52
5          NaN     201005         78         75         85
6          NaN     201006         58         96         60
7          NaN     201007         95         70         80
8          NaN     201008         71         73         51
9          NaN     201009         81         52         62
10         NaN     201010         51         87         80
11         NaN     201011         89         94         56
12         NaN     201012         69         98         51
13         NaN     201013         98         99         77
14         NaN     201014         62         60         54
15         NaN     201015         53         58         

In [33]:
import numpy as np
import pandas as pd
data = pd.read_csv("sample.csv")
print(data)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66


In [34]:
# 인덱스 설정 : set_index()
data2 = pd.read_csv("sample.csv")
data2 = data.set_index("학번", drop = False)
print(data2)

            학번  프로그래밍기초  빅데이터분석  AI활용
학번                                   
201001  201001       64      60    84
201002  201002       98      55    79
201003  201003       82      94   100
201004  201004       69      93    52
201005  201005       78      75    85
201006  201006       58      96    60
201007  201007       95      70    80
201008  201008       71      73    51
201009  201009       81      52    62
201010  201010       51      87    80
201011  201011       89      94    56
201012  201012       69      98    51
201013  201013       98      99    77
201014  201014       62      60    54
201015  201015       53      58    62
201016  201016       81      88    87
201017  201017       53      74    98
201018  201018       56      67    68
201019  201019       87      65    70
201020  201020       50      54    66


In [35]:
# 인덱스 설정 : set_index()
data2 = pd.read_csv("sample.csv")
data2 = data.set_index("학번", drop = True)
print(data2)

        프로그래밍기초  빅데이터분석  AI활용
학번                           
201001       64      60    84
201002       98      55    79
201003       82      94   100
201004       69      93    52
201005       78      75    85
201006       58      96    60
201007       95      70    80
201008       71      73    51
201009       81      52    62
201010       51      87    80
201011       89      94    56
201012       69      98    51
201013       98      99    77
201014       62      60    54
201015       53      58    62
201016       81      88    87
201017       53      74    98
201018       56      67    68
201019       87      65    70
201020       50      54    66


In [36]:
# 뒤 섞인 인덱스를 순차적으로 다시 설정 : reset_index()
data2 = pd.read_csv("sample.csv")
data2 = data.set_index("학번", drop = False)

print(data2)

data2 = data.reset_index(drop = False)

print(data2)

            학번  프로그래밍기초  빅데이터분석  AI활용
학번                                   
201001  201001       64      60    84
201002  201002       98      55    79
201003  201003       82      94   100
201004  201004       69      93    52
201005  201005       78      75    85
201006  201006       58      96    60
201007  201007       95      70    80
201008  201008       71      73    51
201009  201009       81      52    62
201010  201010       51      87    80
201011  201011       89      94    56
201012  201012       69      98    51
201013  201013       98      99    77
201014  201014       62      60    54
201015  201015       53      58    62
201016  201016       81      88    87
201017  201017       53      74    98
201018  201018       56      67    68
201019  201019       87      65    70
201020  201020       50      54    66
    index      학번  프로그래밍기초  빅데이터분석  AI활용
0       0  201001       64      60    84
1       1  201002       98      55    79
2       2  201003       82      94   100


In [37]:
# 뒤 섞인 인덱스를 순차적으로 다시 설정 : reset_index()
data2 = pd.read_csv("sample.csv")
data2 = data.set_index("학번", drop = True)

print(data2)

data2 = data.reset_index(drop = True)

print(data2)

        프로그래밍기초  빅데이터분석  AI활용
학번                           
201001       64      60    84
201002       98      55    79
201003       82      94   100
201004       69      93    52
201005       78      75    85
201006       58      96    60
201007       95      70    80
201008       71      73    51
201009       81      52    62
201010       51      87    80
201011       89      94    56
201012       69      98    51
201013       98      99    77
201014       62      60    54
201015       53      58    62
201016       81      88    87
201017       53      74    98
201018       56      67    68
201019       87      65    70
201020       50      54    66
        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62


In [40]:
# 데이터 전체 보기 및 size 확인: dataframe.size
data = pd.read_csv("sample.csv")
print(data)
print("데이터의 전체 크기는", data.size)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66
데이터의 전체 크기는 80


In [43]:
# 데이터 columns 확인: DataFrame.columns
data = pd.read_csv("sample.csv")
data_col = data.columns
print(data_col)

data_len = len(data.columns)
print(data_len)

Index(['학번', '프로그래밍기초', '빅데이터분석', 'AI활용'], dtype='object')
4


In [46]:
# 데이터 values 확인: DataFrame.values
data = pd.read_csv("sample.csv")
data_val = data.values
print(data_val)

data_len = len(data.values)
print(data_len)

[[201001     64     60     84]
 [201002     98     55     79]
 [201003     82     94    100]
 [201004     69     93     52]
 [201005     78     75     85]
 [201006     58     96     60]
 [201007     95     70     80]
 [201008     71     73     51]
 [201009     81     52     62]
 [201010     51     87     80]
 [201011     89     94     56]
 [201012     69     98     51]
 [201013     98     99     77]
 [201014     62     60     54]
 [201015     53     58     62]
 [201016     81     88     87]
 [201017     53     74     98]
 [201018     56     67     68]
 [201019     87     65     70]
 [201020     50     54     66]]
20


In [51]:
# column 데이터 선택 : DataFrame.열이름
data = pd.read_csv("sample.csv")
# data_1 = data["프로그래밍기초"]
# print(data_1)

data_2 = data.프로그래밍기초
print(data_2)

data_3 = data[["프로그래밍기초", "AI활용"]]
print(data_3)

0     64
1     98
2     82
3     69
4     78
5     58
6     95
7     71
8     81
9     51
10    89
11    69
12    98
13    62
14    53
15    81
16    53
17    56
18    87
19    50
Name: 프로그래밍기초, dtype: int64
    프로그래밍기초  AI활용
0        64    84
1        98    79
2        82   100
3        69    52
4        78    85
5        58    60
6        95    80
7        71    51
8        81    62
9        51    80
10       89    56
11       69    51
12       98    77
13       62    54
14       53    62
15       81    87
16       53    98
17       56    68
18       87    70
19       50    66


In [54]:
# DataFrame의 행은 인덱스의 슬라이싱을 통해 얻을 수 있다.
data = pd.read_csv("sample.csv")
print(data)
data_1 = data[0:5]
print(data_1)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66
       학번  프로그래밍기초  빅데이터분석  AI활용
0  201001       64      60    84
1  201002       98      55    79
2  201003       82      94   100
3  201004       69      93    52
4  201005       78      75    85


In [58]:
# DataFrame.loc[행 인덱스 : 행 인덱스, ['열 이름', '열 이름'] ]

data = pd.read_csv("sample.csv")
# print(data)
data_1 = data.loc[0]
print(data_1)

data_2 = data.loc[0:3, ["빅데이터분석","프로그래밍기초"]]
print(data_2)

학번         201001
프로그래밍기초        64
빅데이터분석         60
AI활용           84
Name: 0, dtype: int64
   빅데이터분석  프로그래밍기초
0      60       64
1      55       98
2      94       82
3      93       69


In [63]:
data = pd.read_csv("sample.csv")
print(data)
# data_1 = data.iloc[0,3] # 0, AI
data_1 = data.iloc[0,1:4] # 1번 인덱 ~ 4번 인덱 앞까지(3)
print(data_1)

data_2 = data.iloc[0:3,[1,3]]
print(data_2)

data_3 = data.iloc[[2,4,10],[1,2]]
print(data_3)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66
프로그래밍기초    64
빅데이터분석     60
AI활용       84
Name: 0, dtype: int64
   프로그래밍기초  AI활용
0       64    84
1       98    79
2       82   100
    프로그래밍기초  빅데이터분석
2        82      94
4        78      75
10       89      94


In [64]:
data = pd.read_csv("sample.csv")
print(data)
data_1 = data.loc[1:5]
data_2 = data.iloc[1:5]
print(data_1)
print(data_2)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66
       학번  프로그래밍기초  빅데이터분석  AI활용
1  201002       98      55    79
2  201003       82      94   100
3  201004       69      93    52
4  201005       78      75    85
5  201006       58      96    60
       학번  프로그래밍기초  빅데이터분석  AI활용
1  201002       98      55    79
2  201003       82    

In [67]:
data = pd.read_csv("sample.csv")
data_1 = data.loc[0, ['빅데이터분석']] # 열 이름 가능
print(data_1)


data_2 = data.iloc[2, [1]] # 숫자
print(data_2)

data_3 = data.at[0, '빅데이터분석']
print(data_3)

data_4 = data.iat[2, 1]
print(data_4)

빅데이터분석    60
Name: 0, dtype: int64
프로그래밍기초    82
Name: 2, dtype: int64
60
82


In [74]:
data = pd.read_csv('sample.csv')
print(data)

data_1 = data.loc[0:3, ['빅데이터분석']]
print(data_1)

data_2 = data.iloc[0:3, [2]]
print(data_2)

data_3 = data.at[0, '빅데이터분석']
print(data_3)

data_4 = data.iat[2, 1]
print(data_4)

        학번  프로그래밍기초  빅데이터분석  AI활용
0   201001       64      60    84
1   201002       98      55    79
2   201003       82      94   100
3   201004       69      93    52
4   201005       78      75    85
5   201006       58      96    60
6   201007       95      70    80
7   201008       71      73    51
8   201009       81      52    62
9   201010       51      87    80
10  201011       89      94    56
11  201012       69      98    51
12  201013       98      99    77
13  201014       62      60    54
14  201015       53      58    62
15  201016       81      88    87
16  201017       53      74    98
17  201018       56      67    68
18  201019       87      65    70
19  201020       50      54    66
   빅데이터분석
0      60
1      55
2      94
3      93
   빅데이터분석
0      60
1      55
2      94
60
82
