In [1]:
# 16
class TestClass2:
    def __init__(self, name, email):
        self.name = name
        self.email = email
        
hong = TestClass2("홍길동", "test@korea.com")
print("이름:%s" % hong.name)
print("이름:%s" % hong.email)

이름:홍길동
이름:test@korea.com


In [9]:
# 17
import numpy as np
df2 = np.array(np.arange(0, 12).reshape(4, 3))
# 1출력
print(df2)

# 2출력
df2[df2>5] = 0
print(df2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]
 [0 0 0]
 [0 0 0]]


In [25]:
import pandas as pd
df = {"city" : ["서울", "부산", "대전", "대구", "광주"],
      "year" : [2017, 2017, 2018, 2018, 2018],
      "temp" : [18, 20, 19, 21, 20]}

df = pd.DataFrame(df)

# 1
print(df)

# 2
car = [50, 40, 20, 30, 10]
df["car"] = car

print(df)

# 3
print(df["temp"].value_counts())

  city  year  temp
0   서울  2017    18
1   부산  2017    20
2   대전  2018    19
3   대구  2018    21
4   광주  2018    20
  city  year  temp  car
0   서울  2017    18   50
1   부산  2017    20   40
2   대전  2018    19   20
3   대구  2018    21   30
4   광주  2018    20   10
20    2
18    1
19    1
21    1
Name: temp, dtype: int64
